print("__________BIODATA_DETAILS__________")
Name=input("Enter yor name")
Age=int(input("Enter The age"))
Address=input("Enter the your ADDRESS")
Contact_no=int(input("enter the Contact_no"))   
salary=float(input("Enter your salary"))
Company_Name=input("Company_Name:")
Location=input("Location:")

print("Name is :",Name)
print("Age is ",Age)
print("Address is :",Address)
print("ContactNo:",Contact_no)
print("salary is :",salary)
print("Company_name is:",Company_Name)
print("Location is:",Location)